name: l3gx
description: Driver for L3Gx(L3GD20/L3G4200D) 3-axis gyroscope sensors
groups:
  - imu
code_owners: 
  - qb4-dev
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - name: esp32
  - name: esp8266
  - name: esp32s2
  - name: esp32c3
license: BSD-3
copyrights:
  - name: qb4-dev
    year: 2023
