---

# see https://github.com/fuxingloh/multi-labeler
version: v1
labels:

  # thses labels are used to draft relases.
  - label: "enhancement"
    matcher:
      branch: "^(feat|feature)-.*"
  - label: "bugfix"
    matcher:
      branch: "^(bugfix|fix)-.*"
  - label: "doc"
    matcher:
      branch: "^(doc|documentation)-.*"
  - label: "ci"
    matcher:
      branch: "^ci-.*"
  - label: "chore"
    matcher:
      branch: "^chore-.*"

  # area indicates which files are modified in the PR.
  - label: "area:docs"
    sync: true
    matcher:
      files:
        any:
          - "docs/**"
          - "*.md"
  - label: "area:docs-only"
    sync: true
    matcher:
      files:
        any:
          - "docs/**"
          - "*.md"
        all:
          - "!components"
  - label: "area:ci"
    sync: true
    matcher:
      files:
        - ".github/**"
  - label: "area:components"
    sync: true
    matcher:
      files: "components/**"
