---

# see https://github.com/fuxingloh/multi-labeler for details
version: v1
labels:
  - label: "enhancement"
    matcher:
      branch: "^(feat|feature)-.*"
  - label: "bugfix"
    matcher:
      branch: "^(bugfix|fix)-.*"
  - label: "doc"
    matcher:
      branch: "^(doc|documentation)-.*"
  - label: "ci"
    matcher:
      branch: "^ci-.*"
  - label: "chore"
    matcher:
      branch: "^chore-.*"
