---

# see https://github.com/fuxingloh/multi-labeler
version: v1
labels:

  # these labels are used to draft releases.
  - label: "enhancement"
    matcher:
      branch: "^(feat|feature)-.*"
  - label: "bugfix"
    matcher:
      branch: "^(bugfix|fix)-.*"
  - label: "doc"
    matcher:
      branch: "^(doc|documentation)-.*"
  - label: "ci"
    matcher:
      branch: "^ci-.*"
  - label: "chore"
    matcher:
      branch: "^chore-.*"

  # area indicates which files are modified in the PR.
  - label: "area:docs"
    sync: true
    matcher:
      files:
        any:
          - "docs/**"
          - "*.md"
  - label: "area:docs-only"
    sync: true
    matcher:
      files:
        any:
          - "docs/**"
          - "*.md"
        all:
          - "!components"
          - "!.github/**"
  - label: "area:ci"
    sync: true
    matcher:
      files:
        - ".github/**"
  - label: "area:components"
    sync: true
    matcher:
      files: "components/**"
  - label: "area:components:ads111x"
    sync: true
    matcher:
      files:
        any:
          - "components/ads111x/**"
          - "components/ads111x/.eil.yml"
          - "examples/ads111x/**"
  - label: "area:components:aht"
    sync: true
    matcher:
      files:
        any:
          - "components/aht/**"
          - "components/aht/.eil.yml"
          - "examples/aht/**"
  - label: "area:components:bh1750"
    sync: true
    matcher:
      files:
        any:
          - "components/bh1750/**"
          - "components/bh1750/.eil.yml"
          - "examples/bh1750/**"
  - label: "area:components:bh1900nux"
    sync: true
    matcher:
      files:
        any:
          - "components/bh1900nux/**"
          - "components/bh1900nux/.eil.yml"
          - "examples/bh1900nux/**"
  - label: "area:components:bme680"
    sync: true
    matcher:
      files:
        any:
          - "components/bme680/**"
          - "components/bme680/.eil.yml"
          - "examples/bme680/**"
  - label: "area:components:bmp180"
    sync: true
    matcher:
      files:
        any:
          - "components/bmp180/**"
          - "components/bmp180/.eil.yml"
          - "examples/bmp180/**"
  - label: "area:components:bmp280"
    sync: true
    matcher:
      files:
        any:
          - "components/bmp280/**"
          - "components/bmp280/.eil.yml"
          - "examples/bmp280/**"
  - label: "area:components:button"
    sync: true
    matcher:
      files:
        any:
          - "components/button/**"
          - "components/button/.eil.yml"
          - "examples/button/**"
  - label: "area:components:ccs811"
    sync: true
    matcher:
      files:
        any:
          - "components/ccs811/**"
          - "components/ccs811/.eil.yml"
          - "examples/ccs811/**"
  - label: "area:components:color"
    sync: true
    matcher:
      files:
        any:
          - "components/color/**"
          - "components/color/.eil.yml"
          - "examples/color/**"
  - label: "area:components:dht"
    sync: true
    matcher:
      files:
        any:
          - "components/dht/**"
          - "components/dht/.eil.yml"
          - "examples/dht/**"
  - label: "area:components:dps310"
    sync: true
    matcher:
      files:
        any:
          - "components/dps310/**"
          - "components/dps310/.eil.yml"
          - "examples/dps310/**"
  - label: "area:components:ds1302"
    sync: true
    matcher:
      files:
        any:
          - "components/ds1302/**"
          - "components/ds1302/.eil.yml"
          - "examples/ds1302/**"
  - label: "area:components:ds1307"
    sync: true
    matcher:
      files:
        any:
          - "components/ds1307/**"
          - "components/ds1307/.eil.yml"
          - "examples/ds1307/**"
  - label: "area:components:ds18x20"
    sync: true
    matcher:
      files:
        any:
          - "components/ds18x20/**"
          - "components/ds18x20/.eil.yml"
          - "examples/ds18x20/**"
  - label: "area:components:ds3231"
    sync: true
    matcher:
      files:
        any:
          - "components/ds3231/**"
          - "components/ds3231/.eil.yml"
          - "examples/ds3231/**"
  - label: "area:components:ds3502"
    sync: true
    matcher:
      files:
        any:
          - "components/ds3502/**"
          - "components/ds3502/.eil.yml"
          - "examples/ds3502/**"
  - label: "area:components:encoder"
    sync: true
    matcher:
      files:
        any:
          - "components/encoder/**"
          - "components/encoder/.eil.yml"
          - "examples/encoder/**"
  - label: "area:components:esp_idf_lib_helpers"
    sync: true
    matcher:
      files:
        any:
          - "components/esp_idf_lib_helpers/**"
          - "components/esp_idf_lib_helpers/.eil.yml"
          - "examples/esp_idf_lib_helpers/**"
  - label: "area:components:example"
    sync: true
    matcher:
      files:
        any:
          - "components/example/**"
          - "components/example/.eil.yml"
          - "examples/example/**"
  - label: "area:components:framebuffer"
    sync: true
    matcher:
      files:
        any:
          - "components/framebuffer/**"
          - "components/framebuffer/.eil.yml"
          - "examples/framebuffer/**"
  - label: "area:components:hd44780"
    sync: true
    matcher:
      files:
        any:
          - "components/hd44780/**"
          - "components/hd44780/.eil.yml"
          - "examples/hd44780/**"
  - label: "area:components:hdc1000"
    sync: true
    matcher:
      files:
        any:
          - "components/hdc1000/**"
          - "components/hdc1000/.eil.yml"
          - "examples/hdc1000/**"
  - label: "area:components:hmc5883l"
    sync: true
    matcher:
      files:
        any:
          - "components/hmc5883l/**"
          - "components/hmc5883l/.eil.yml"
          - "examples/hmc5883l/**"
  - label: "area:components:ht16k33"
    sync: true
    matcher:
      files:
        any:
          - "components/ht16k33/**"
          - "components/ht16k33/.eil.yml"
          - "examples/ht16k33/**"
  - label: "area:components:hts221"
    sync: true
    matcher:
      files:
        any:
          - "components/hts221/**"
          - "components/hts221/.eil.yml"
          - "examples/hts221/**"
  - label: "area:components:hx711"
    sync: true
    matcher:
      files:
        any:
          - "components/hx711/**"
          - "components/hx711/.eil.yml"
          - "examples/hx711/**"
  - label: "area:components:i2cdev"
    sync: true
    matcher:
      files:
        any:
          - "components/i2cdev/**"
          - "components/i2cdev/.eil.yml"
          - "examples/i2cdev/**"
  - label: "area:components:ina219"
    sync: true
    matcher:
      files:
        any:
          - "components/ina219/**"
          - "components/ina219/.eil.yml"
          - "examples/ina219/**"
  - label: "area:components:ina260"
    sync: true
    matcher:
      files:
        any:
          - "components/ina260/**"
          - "components/ina260/.eil.yml"
          - "examples/ina260/**"
  - label: "area:components:ina3221"
    sync: true
    matcher:
      files:
        any:
          - "components/ina3221/**"
          - "components/ina3221/.eil.yml"
          - "examples/ina3221/**"
  - label: "area:components:lc709203f"
    sync: true
    matcher:
      files:
        any:
          - "components/lc709203f/**"
          - "components/lc709203f/.eil.yml"
          - "examples/lc709203f/**"
  - label: "area:components:led_strip"
    sync: true
    matcher:
      files:
        any:
          - "components/led_strip/**"
          - "components/led_strip/.eil.yml"
          - "examples/led_strip/**"
  - label: "area:components:led_strip_spi"
    sync: true
    matcher:
      files:
        any:
          - "components/led_strip_spi/**"
          - "components/led_strip_spi/.eil.yml"
          - "examples/led_strip_spi/**"
  - label: "area:components:lib8tion"
    sync: true
    matcher:
      files:
        any:
          - "components/lib8tion/**"
          - "components/lib8tion/.eil.yml"
          - "examples/lib8tion/**"
  - label: "area:components:lm75"
    sync: true
    matcher:
      files:
        any:
          - "components/lm75/**"
          - "components/lm75/.eil.yml"
          - "examples/lm75/**"
  - label: "area:components:ls7366r"
    sync: true
    matcher:
      files:
        any:
          - "components/ls7366r/**"
          - "components/ls7366r/.eil.yml"
          - "examples/ls7366r/**"
  - label: "area:components:max31725"
    sync: true
    matcher:
      files:
        any:
          - "components/max31725/**"
          - "components/max31725/.eil.yml"
          - "examples/max31725/**"
  - label: "area:components:max31855"
    sync: true
    matcher:
      files:
        any:
          - "components/max31855/**"
          - "components/max31855/.eil.yml"
          - "examples/max31855/**"
  - label: "area:components:max31865"
    sync: true
    matcher:
      files:
        any:
          - "components/max31865/**"
          - "components/max31865/.eil.yml"
          - "examples/max31865/**"
  - label: "area:components:max7219"
    sync: true
    matcher:
      files:
        any:
          - "components/max7219/**"
          - "components/max7219/.eil.yml"
          - "examples/max7219/**"
  - label: "area:components:mcp23008"
    sync: true
    matcher:
      files:
        any:
          - "components/mcp23008/**"
          - "components/mcp23008/.eil.yml"
          - "examples/mcp23008/**"
  - label: "area:components:mcp23x17"
    sync: true
    matcher:
      files:
        any:
          - "components/mcp23x17/**"
          - "components/mcp23x17/.eil.yml"
          - "examples/mcp23x17/**"
  - label: "area:components:mcp342x"
    sync: true
    matcher:
      files:
        any:
          - "components/mcp342x/**"
          - "components/mcp342x/.eil.yml"
          - "examples/mcp342x/**"
  - label: "area:components:mcp4725"
    sync: true
    matcher:
      files:
        any:
          - "components/mcp4725/**"
          - "components/mcp4725/.eil.yml"
          - "examples/mcp4725/**"
  - label: "area:components:mcp960x"
    sync: true
    matcher:
      files:
        any:
          - "components/mcp960x/**"
          - "components/mcp960x/.eil.yml"
          - "examples/mcp960x/**"
  - label: "area:components:mcp9808"
    sync: true
    matcher:
      files:
        any:
          - "components/mcp9808/**"
          - "components/mcp9808/.eil.yml"
          - "examples/mcp9808/**"
  - label: "area:components:mhz19b"
    sync: true
    matcher:
      files:
        any:
          - "components/mhz19b/**"
          - "components/mhz19b/.eil.yml"
          - "examples/mhz19b/**"
  - label: "area:components:ms5611"
    sync: true
    matcher:
      files:
        any:
          - "components/ms5611/**"
          - "components/ms5611/.eil.yml"
          - "examples/ms5611/**"
  - label: "area:components:noise"
    sync: true
    matcher:
      files:
        any:
          - "components/noise/**"
          - "components/noise/.eil.yml"
          - "examples/noise/**"
  - label: "area:components:onewire"
    sync: true
    matcher:
      files:
        any:
          - "components/onewire/**"
          - "components/onewire/.eil.yml"
          - "examples/onewire/**"
  - label: "area:components:pca9557"
    sync: true
    matcher:
      files:
        any:
          - "components/pca9557/**"
          - "components/pca9557/.eil.yml"
          - "examples/pca9557/**"
  - label: "area:components:pca9685"
    sync: true
    matcher:
      files:
        any:
          - "components/pca9685/**"
          - "components/pca9685/.eil.yml"
          - "examples/pca9685/**"
  - label: "area:components:pcf8563"
    sync: true
    matcher:
      files:
        any:
          - "components/pcf8563/**"
          - "components/pcf8563/.eil.yml"
          - "examples/pcf8563/**"
  - label: "area:components:pcf8574"
    sync: true
    matcher:
      files:
        any:
          - "components/pcf8574/**"
          - "components/pcf8574/.eil.yml"
          - "examples/pcf8574/**"
  - label: "area:components:pcf8575"
    sync: true
    matcher:
      files:
        any:
          - "components/pcf8575/**"
          - "components/pcf8575/.eil.yml"
          - "examples/pcf8575/**"
  - label: "area:components:pcf8591"
    sync: true
    matcher:
      files:
        any:
          - "components/pcf8591/**"
          - "components/pcf8591/.eil.yml"
          - "examples/pcf8591/**"
  - label: "area:components:qmc5883l"
    sync: true
    matcher:
      files:
        any:
          - "components/qmc5883l/**"
          - "components/qmc5883l/.eil.yml"
          - "examples/qmc5883l/**"
  - label: "area:components:rda5807m"
    sync: true
    matcher:
      files:
        any:
          - "components/rda5807m/**"
          - "components/rda5807m/.eil.yml"
          - "examples/rda5807m/**"
  - label: "area:components:scd30"
    sync: true
    matcher:
      files:
        any:
          - "components/scd30/**"
          - "components/scd30/.eil.yml"
          - "examples/scd30/**"
  - label: "area:components:scd4x"
    sync: true
    matcher:
      files:
        any:
          - "components/scd4x/**"
          - "components/scd4x/.eil.yml"
          - "examples/scd4x/**"
  - label: "area:components:sgp40"
    sync: true
    matcher:
      files:
        any:
          - "components/sgp40/**"
          - "components/sgp40/.eil.yml"
          - "examples/sgp40/**"
  - label: "area:components:sht3x"
    sync: true
    matcher:
      files:
        any:
          - "components/sht3x/**"
          - "components/sht3x/.eil.yml"
          - "examples/sht3x/**"
  - label: "area:components:sht4x"
    sync: true
    matcher:
      files:
        any:
          - "components/sht4x/**"
          - "components/sht4x/.eil.yml"
          - "examples/sht4x/**"
  - label: "area:components:si7021"
    sync: true
    matcher:
      files:
        any:
          - "components/si7021/**"
          - "components/si7021/.eil.yml"
          - "examples/si7021/**"
  - label: "area:components:sts21"
    sync: true
    matcher:
      files:
        any:
          - "components/sts21/**"
          - "components/sts21/.eil.yml"
          - "examples/sts21/**"
  - label: "area:components:tca9548"
    sync: true
    matcher:
      files:
        any:
          - "components/tca9548/**"
          - "components/tca9548/.eil.yml"
          - "examples/tca9548/**"
  - label: "area:components:tca95x5"
    sync: true
    matcher:
      files:
        any:
          - "components/tca95x5/**"
          - "components/tca95x5/.eil.yml"
          - "examples/tca95x5/**"
  - label: "area:components:tda74xx"
    sync: true
    matcher:
      files:
        any:
          - "components/tda74xx/**"
          - "components/tda74xx/.eil.yml"
          - "examples/tda74xx/**"
  - label: "area:components:tsl2561"
    sync: true
    matcher:
      files:
        any:
          - "components/tsl2561/**"
          - "components/tsl2561/.eil.yml"
          - "examples/tsl2561/**"
  - label: "area:components:tsl2591"
    sync: true
    matcher:
      files:
        any:
          - "components/tsl2591/**"
          - "components/tsl2591/.eil.yml"
          - "examples/tsl2591/**"
  - label: "area:components:tsl4531"
    sync: true
    matcher:
      files:
        any:
          - "components/tsl4531/**"
          - "components/tsl4531/.eil.yml"
          - "examples/tsl4531/**"
  - label: "area:components:tsys01"
    sync: true
    matcher:
      files:
        any:
          - "components/tsys01/**"
          - "components/tsys01/.eil.yml"
          - "examples/tsys01/**"
  - label: "area:components:ultrasonic"
    sync: true
    matcher:
      files:
        any:
          - "components/ultrasonic/**"
          - "components/ultrasonic/.eil.yml"
          - "examples/ultrasonic/**"
  - label: "area:components:wiegand"
    sync: true
    matcher:
      files:
        any:
          - "components/wiegand/**"
          - "components/wiegand/.eil.yml"
          - "examples/wiegand/**"
  - label: "area:components:ads130e08"
    sync: true
    matcher:
      files:
        any:
          - "components/ads130e08/**"
          - "components/ads130e08/.eil.yml"
          - "examples/ads130e08/**"
