---
# automatically label PRs by branch name. prefix the branch name with one of
# these prefixes.

enhancement:
  - "feature-*"
  - "feat-*"
bugfix:
  - "fix-*"
  - "bugfix-*"
chore: "chore-*"
ci:
  - "ci-*"
documentation:
  - "documentation-*"
  - "doc-*"
