---
name: bmi160
description: Driver for BMI160 6-DOF IMU
version: 1.0.0
groups:
  - imu
code_owners: lukbieli
depends:
  - log
  - esp_idf_lib_helpers
  - i2cdev
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
  - esp32s3
  - esp32c2
  - esp32c6
  - esp32h2
  - esp32p4
  - esp32c5
  - esp32c61
license: ISC
copyrights:
  - name: lukbieli
    year: 2025
