name: qmi8658c
description: Driver for QMI8658C 6-axis IMU sensor
version: 0.5.0
groups:
  - magnetic
code_owners: xyzroe
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp32c3
  - esp8266
  - esp32s2
  - esp32c3
  - esp32c6
license: BSD-3
copyrights:
  - name: xyzroe
    year: 2024