---
components:
  - name: si7021
    description: |
      Driver for Si7013/Si7020/Si7021/HTU2xD/SHT2x and compatible temperature
      and humidity sensors
    group: temperature
    groups:
      - name: humidity
    code_owners: UncleRus
    depends:
      - i2cdev
      - log
      - esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp32c3
      - name: esp8266
      - name: esp32s2
      - name: esp32c3
    licenses:
      - name: BSD-3
    copyrights:
      - author:
          name: UncleRus
        year: 2019
