name: husb238
description: Driver for HUSB238 USB PD Sink Controller
version: 1.0.0
groups:
  - current
code_owners: xyzroe
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp32c3
  - esp8266
  - esp32s2
  - esp32c3
  - esp32c6
license: BSD-3
copyrights:
  - name: xyzroe
    year: 2025
