name: lsm303
description: Driver for LSM303 3-axis accelerometer and magnetometer sensor
version: 1.0.0
groups:
  - imu
  - magnetic
code_owners: 
  - qb4-dev
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: qb4-dev
    year: 2023
