---
components:
  - name: htu21d
    description: |
      Driver for HTU21D(F) temperature and humidity sensor.
    group: temperature
    groups:
      - humidity
    code_owners:
      -name: saasaa
    depends:
      - name: i2cdev
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: N/A
    targets:
      - name: esp32
    licenses:
      - name: ISC
    copyrights:
      - name: saasaa
        year: 2022
