---
components:
  - name: pca9685
    description: Driver for 16-channel, 12-bit PWM PCA9685
    group: misc
    groups: []
    code_owners: UncleRus
    depends:
      - i2cdev
      - log
      - esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
      - name: esp32s2
      - name: esp32c3
    licenses:
      - name: BSD-3
    copyrights:
      - author:
          name: UncleRus
        year: 2016
