---
name: sts3x
description: Driver for Sensirion STS30/STS31/STS35 digital temperature sensor
version: 1.0.0
groups:
  - temperature
code_owners: slimcdk
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
  - esp32s3
  - esp32c2
  - esp32c6
  - esp32h2
  - esp32p4
  - esp32c5
  - esp32c61
license: BSD-3
copyrights:
  - name: gschorcht
    year: 2017
  - name: UncleRus
    year: 2019
  - name: slimcdk
    year: 2023
