---
components:
  - name: ads111x
    description: |
      Driver for ADS1113/ADS1114/ADS1115 and ADS1013/ADS1014/ADS1015 I2C ADC
    group: adc-dac
    groups: []
    code_owners: UncleRus
    depends:
      - name: i2cdev
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
      - name: esp32s2
      - name: esp32c3
    licenses:
      - name: BSD-3
    copyrights:
      - author:
          name: UncleRus
        year: 2016
      - name: dianlight
        year: 2020
