---
name: pcf8575
description: Driver for PCF8575 remote 16-bit I/O expander for I2C-bus
version: 1.0.0
groups:
  - gpio
code_owners: UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
  - esp32s3
  - esp32c2
  - esp32c6
  - esp32h2
  - esp32p4
  - esp32c5
  - esp32c61
license: MIT
copyrights:
  - name: UncleRus
    year: 2019
