---
components:
  - name: esp_idf_lib_helpers
    description: |
      Common support library for esp-idf-lib
    group: common
    groups: []
    code_owners:
      - name: UncleRus
      - name: trombik
    depends:
      - name: freertos
    thread_safe: N/A
    targets:
      - name: esp32
      - name: esp8266
      - name: esp32s2
      - name: esp32c3
    licenses:
      - name: ISC
    copyrights:
      - name: trombik
        year: 2019
